name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Run eslint
        run: npm run lint:check
      - name: Run prettier
        run: npm run format:check

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
